# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170220_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkproduct',
            name='serial_number',
            field=models.TextField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='rentalproduct',
            name='serial_number',
            field=models.TextField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='uniqueproduct',
            name='serial_number',
            field=models.TextField(blank=True, default=0),
        ),
    ]
