# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productpictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpictures',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='catalog.Product'),
        ),
    ]
